openapi: 3.0.0
info:
  title: Notification Service API
  version: 1.0.0
  description: API for sending and managing notifications (email, SMS, push).
servers:
  - url: http://localhost:3003
    description: Local server
paths:
  /notifications:
    get:
      summary: Get all notifications for the authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of notifications
    post:
      summary: Send a notification (admin only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: [email, sms, push]
                userId:
                  type: string
                title:
                  type: string
                message:
                  type: string
                priority:
                  type: string
                  enum: [low, medium, high]
                metadata:
                  type: object
      responses:
        '201':
          description: Notification sent
  /notifications/{id}:
    get:
      summary: Get a specific notification
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Notification details
    delete:
      summary: Delete a notification
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Notification deleted
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 